theme: jekyll-theme-cayman
show_downloads: true

# Setup
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Jakob Bradshaw
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate